name = "nimu-generation-worker"
main = "src/worker.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[env.development]
name = "nimu-generation-worker-dev"

[env.production]
name = "nimu-generation-worker-prod"

# Durable Objects bindings
[[durable_objects.bindings]]
name = "JOB_MANAGER"
class_name = "JobManagerDO"
script_name = "nimu-generation-worker"

[[durable_objects.bindings]]
name = "QUEUE_MANAGER"
class_name = "QueueManagerDO"
script_name = "nimu-generation-worker"

# Durable Objects classes
[[migrations]]
tag = "v1"
new_sqlite_classes = ["JobManagerDO", "QueueManagerDO"]

# R2 bucket bindings
[[r2_buckets]]
binding = "VIDEO_STORAGE"
bucket_name = "nimu-videos"
preview_bucket_name = "nimu-videos-dev"

# Cron triggers for cleanup
[triggers]
crons = ["0 2 * * *"] # Daily at 2 AM UTC for cleanup

# KV namespace for configuration (optional) - commented out for now
# [[kv_namespaces]]
# binding = "CONFIG"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Environment variables (secrets)
[vars]
ENVIRONMENT = "development"
MAX_CONCURRENT_JOBS = "3"
JOB_TIMEOUT = "300000" # 5 minutes
CLEANUP_RETENTION_DAYS = "7"
MAX_FILE_SIZE = "524288000" # 500MB in bytes
R2_BASE_URL = "https://nimu-videos.your-domain.com" # Replace with your actual domain
THUMBNAIL_GENERATION_ENABLED = "true"

# Build configuration
[build]
command = "npm run build"

# Development configuration
[dev]
ip = "127.0.0.1"
port = 8787
local_protocol = "http"

# wrangler.toml (wrangler v3.88.0^)
[observability]
enabled = false


[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true